-- Prod 1
INSERT INTO PRODUCT 
(ID, NAME, DESCRIPTION, BRAND, MAX_QUANTITY, MIN_QUANTITY, QUANTITY, WEIGHT)
VALUES (1001,'Product Y', 'This is a fantastic product', 'ABC Corporation',100,10,55,1);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1001,1001,'FIRST REGISTER', 0,50);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1002,1001,'STOCK UP', 0,10);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1003,1001,'SOLD', 1,5);

-- Prod 2 
INSERT INTO PRODUCT 
(ID, NAME, DESCRIPTION, BRAND, MAX_QUANTITY, MIN_QUANTITY, QUANTITY, WEIGHT)
VALUES (1002,'Product Z', 'This is a fantastic product', 'ABC Corporation',100,10,55,1);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1004,1002,'FIRST REGISTER', 0,50);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1005,1002,'STOCK UP', 0,10);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1006,1002,'SOLD', 1,5);

-- Prod 3
INSERT INTO PRODUCT 
(ID, NAME, DESCRIPTION, BRAND, MAX_QUANTITY, MIN_QUANTITY, QUANTITY, WEIGHT)
VALUES (1003,'Product A', 'This is a fantastic product', 'ABC Corporation',100,10,55,1);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1007,1003,'FIRST REGISTER', 0,50);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1008,1003,'STOCK UP', 0,10);

INSERT INTO INVENTORY_MOVEMENT
(ID, PRODUCT_ID, DESCRIPTION, MOVEMENT_TYPE, QUANTITY)
VALUES(1009,1003,'SOLD', 1,5);